// Red-first fixtures for the laughcounter pack's checks: each rule must fire on a
// violating file set and stay quiet on a clean one. Run directly:
//
//   node --test .claudinite/local/packs/laughcounter/pack.test.mjs
//
// They live here rather than in tests/ (`claudinite-isolation`). The fake ctx is
// the slice of the engine's context a check actually uses — for this rule, just
// `files` — so these tests need neither the canon mount nor a git checkout. The
// real tree is asserted by `check_the_world` itself, which runs the rule over
// `ctx.files` (tracked files plus untracked-not-ignored ones).
import { test } from 'node:test';
import assert from 'node:assert/strict';

import noCommittedArtifacts from './no-committed-artifacts.mjs';

const ctxOf = (files) => ({ files, read: () => null });

test('no-committed-artifacts fires on every shape of build output', () => {
  const findings = noCommittedArtifacts.run(ctxOf([
    'mac/build/LaughCounter.app/Contents/MacOS/LaughCounter',
    'mac/.build/release/LaughCounter.o',
    'reference/__pycache__/detector.cpython-311.pyc',
    'mac/LaughCounter.dmg',
    'docs/.DS_Store',
    'mac/LaughCounter.xcodeproj/project.xcworkspace/xcuserdata/me.xcuserdatad/UserInterfaceState.xcuserstate',
  ]));
  assert.equal(findings.length, 6);
  assert.deepEqual(findings.map((f) => f.file), [
    'mac/build/LaughCounter.app/Contents/MacOS/LaughCounter',
    'mac/.build/release/LaughCounter.o',
    'reference/__pycache__/detector.cpython-311.pyc',
    'mac/LaughCounter.dmg',
    'docs/.DS_Store',
    'mac/LaughCounter.xcodeproj/project.xcworkspace/xcuserdata/me.xcuserdatad/UserInterfaceState.xcuserstate',
  ]);
  assert.match(findings[0].what, /build\/` directory/);
  assert.match(findings[3].what, /build output/);
  assert.match(findings[4].what, /generated by macOS/);
  // The remedy the prose pays for rides on the finding, not just in the header.
  assert.match(findings[0].fix, /before\* dropping its ignore rules/);
  assert.match(findings[0].fix, /git rm --cached/);
});

// The false alarm the check is built to avoid: this repo's own filenames talk
// about building, and a substring match would flag them all.
test('no-committed-artifacts stays quiet on real source that merely says "build"', () => {
  const findings = noCommittedArtifacts.run(ctxOf([
    'mac/scripts/build-app.sh',
    'mac/scripts/notarize-dmg.sh',
    '.github/workflows/build-macos-dmg.yml',
    'dev/procedures/ci-release.md',
    'mac/Sources/LaughCounter/AudioHub.swift',
    'mac/Package.swift',
    'mac/Resources/Info.plist',
    'docs/DESIGN-AND-TRADEOFFS.md',
    '.claudinite/local/packs/laughcounter/no-committed-artifacts.mjs',
    'README.md',
  ]));
  assert.deepEqual(findings, []);
});

// A directory that only *starts* with an artifact name is source, not output.
test('no-committed-artifacts matches whole path segments, not prefixes', () => {
  const findings = noCommittedArtifacts.run(ctxOf([
    'mac/buildsupport/Version.swift',
    'tools/distiller/main.py',
    'mac/Sources/LaughCounter/Builder.swift',
  ]));
  assert.deepEqual(findings, []);
});
